import { StyleSheet } from 'react-native';

// my styles :)

export const about = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 60,
    paddingTop: 60,
    padding: 16,
  },
  shareBtn: {
    width: 142,
    height: 80,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  shareBtnTxt: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  lblAbout: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    textAlign: 'center',
  },
  sbtAbout: {
    fontSize: 16,
    fontFamily: 'Nunito-Medium',
    color: '#7B1166',
    textAlign: 'center',
    marginTop: 10,
  },
  header: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  aboutJellycnt: {
    width: '100%',
    padding: 15,
    paddingBottom: 20,
    backgroundColor: '#fff',
    borderWidth: 5,
    borderColor: '#DF6BC9',
    borderRadius: 50,
  },
});

// styles for feed screen

export const feed = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingBottom: 60,
  },
  header: {
    width: '100%',
    paddingHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 60,
  },
  timerBox: {
    backgroundColor: '#FFF',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 46,
    borderWidth: 3,
    borderColor: '#DF6BC9',
    minHeight: 83,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  timerText: {
    fontSize: 18,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  countBox: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 4,
    borderWidth: 2,
    borderColor: '#DF6BC9',
    position: 'absolute',
    top: -10,
    right: -10,
  },
  nibbo: {
    width: 220,
    height: 220,
    marginTop: 40,
  },
  bubble: {
    backgroundColor: '#E6F7FF',
    borderRadius: 40,
    padding: 20,
    marginTop: -10,
    alignItems: 'center',
  },
  bubbleText: {
    fontSize: 20,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    marginBottom: 4,
    textAlign: 'center',
  },
  requestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
    gap: 8,
  },
  amount: {
    fontSize: 22,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
  bar: {
    flexDirection: 'row',
    gap: 22,
    marginTop: 50,
  },
  fruitBtn: {
    alignItems: 'center',
  },
  count: {
    fontSize: 16,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
});

// styles for game screen

export const jellygame = StyleSheet.create({
  container: {
    flex: 1,
  },
  timerBox: {
    backgroundColor: '#FFF',
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 46,
    borderWidth: 3,
    borderColor: '#DF6BC9',
    minHeight: 83,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    minWidth: 150,
  },
  shareBtn: {
    width: 142,
    height: 80,
    borderRadius: 70,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  shareBtnTxt: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#fff',
    textAlign: 'center',
  },
  timerText: {
    fontSize: 18,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  header: {
    marginTop: 50,
    paddingHorizontal: 20,
    alignItems: 'center',
    zIndex: 10,
  },
  pauseBtn: {
    position: 'absolute',
    left: 20,
  },
  pauseTxt: {
    fontSize: 26,
    color: '#7B1166',
  },
  timer: {
    backgroundColor: '#FFF',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 30,
    borderWidth: 3,
    borderColor: '#DF6BC9',
  },
  timerTxt: {
    fontSize: 20,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
  fruit: {
    position: 'absolute',
    top: 0,
  },
  scoreBox: {
    position: 'absolute',
    bottom: 30,
    alignSelf: 'center',
    backgroundColor: '#FFF',
    borderRadius: 50,
    borderWidth: 5,
    borderColor: '#DF6BC9',
    padding: 20,
    width: 206,
  },
  scoreTitle: {
    fontSize: 18,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
    textAlign: 'center',
    marginBottom: 10,
  },
  scoreRow: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  scoreItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  scoreTxt: {
    fontSize: 18,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
  modalBg: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.47)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBox: {
    backgroundColor: '#FFF',
    borderRadius: 50,
    padding: 22,
    width: '90%',
    alignItems: 'center',
    borderWidth: 5,
    borderColor: '#DF6BC9',
    paddingTop: 8,
  },
  resultBox: {
    backgroundColor: '#FFF',
    borderRadius: 50,
    padding: 14,
    width: '90%',
    alignItems: 'center',
    borderWidth: 5,
    borderColor: '#DF6BC9',
  },
  modalTitle: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    marginBottom: 6,
  },
  resultSubTitle: {
    fontSize: 15,
    fontFamily: 'Nunito-Medium',
    color: '#7B1166',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalBtn: {
    width: 195,
    height: 80,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 10,
    borderWidth: 1,
    borderColor: '#7B1166',
  },
  modalBtnTxt: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  resultTxt: {
    fontSize: 24,
    color: '#7B1166',
    marginVertical: 10,
    fontFamily: 'Nunito-Bold',
  },
  resultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  resultNum: {
    fontSize: 22,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
  feedBtn: {
    marginTop: 20,
    width: 195,
    height: 80,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.3,
    borderColor: '#7B1166',
  },
  feedTxt: {
    fontSize: 22,
    fontFamily: 'Nunito-Black',
    color: '#7B1166',
  },
  infotxt: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'Nunito-Medium',
    marginTop: 20,
    textAlign: 'center',
    position: 'absolute',
    bottom: 40,
    paddingHorizontal: 30,
  },
});

// styles for home screen

export const home = StyleSheet.create({
  jellycreaturecontainer: {
    flex: 1,
    paddingTop: 60,
    alignItems: 'center',
    padding: 16,
  },
  jellycreaturefruitscorecontainer: {
    width: 230,
    backgroundColor: 'white',
    borderWidth: 5,
    borderColor: '#DF6BC9',
    borderRadius: 63,
    padding: 20,
    paddingHorizontal: 22,
    alignItems: 'center',
    justifyContent: 'center',
    height: 200,
  },
  jellycreaturefruittxt: {
    textAlign: 'center',
    marginTop: 10,
    fontSize: 20,
    color: '#7B1166',
    fontFamily: 'Nunito-Black',
  },
  jellycreaturegradbtn: {
    borderRadius: 135,
    width: 90,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#7B1166',
  },
  fruitswrapper: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 20,
  },
  jellynumcont: {
    width: 90,
    height: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  jellynumconttxt: {
    fontSize: 48,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  jellycreaturegradbtnfeed: {
    borderRadius: 65,
    width: 195,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.3,
    borderColor: '#7B1166',
  },
  jellycreaturegradbtnfeedtxt: {
    fontSize: 22,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  homeBubbleText: {
    fontSize: 22,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    textAlign: 'center',
    top: -5,
  },
  dailyOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dailyModal: {
    width: '90%',
    backgroundColor: '#FFF',
    borderRadius: 40,
    padding: 20,
    borderWidth: 4,
    borderColor: '#DF6BC9',
  },
  dailyClose: {
    position: 'absolute',
    right: 12,
    top: 10,
    zIndex: 10,
  },
  dailyTitle: {
    fontSize: 22,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    textAlign: 'center',
    marginBottom: 13,
  },
  dailyText: {
    fontSize: 15,
    fontFamily: 'Nunito-Regular',
    color: '#7B1166',
    marginBottom: 20,
    width: '60%',
  },
  daysRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayItem: {
    fontSize: 14,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  dayActive: {
    color: '#2ECC71',
  },
});

// styles for setup screen

export const setup = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    padding: 16,
    paddingTop: 60,
  },
  header: {
    width: '100%',
    marginBottom: 20,
  },
  box: {
    width: '100%',
    backgroundColor: '#fff',
    borderWidth: 5,
    borderColor: '#DF6BC9',
    borderRadius: 50,
    padding: 20,
    marginTop: 40,
  },
  title: {
    fontSize: 24,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
    textAlign: 'center',
    marginBottom: 20,
  },
  section: {
    fontSize: 20,
    fontFamily: 'Nunito-Bold',
    color: '#7B1166',
  },
  bgRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 13,
  },
  bgCard: {
    width: 96,
    height: 124,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 3.5,
    borderColor: '#DF6BC9',
  },
  bgSelected: {
    borderColor: '#4CD137',
  },
  bgImg: {
    width: '100%',
    height: '100%',
  },
  resetBtn: {
    marginTop: 30,
    width: 260,
    height: 80,
    borderRadius: 60,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#7B1166',
  },
  resetTxt: {
    color: '#fff',
    fontSize: 20,
    fontFamily: 'Nunito-Bold',
  },
  flexdirwrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
  },
});
